services:
  db:
    build:
      context: .
      dockerfile_inline: "FROM postgres:15"
    image: hourglass-local-db:latest
    container_name: hourglass-postgres
    environment:
      POSTGRES_USER: hourglass
      POSTGRES_PASSWORD: hourglass
      POSTGRES_DB: hourglass
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
