export const TUTORIAL_ROUTE_TRANSITION_DELAY_MS = 280;
export const TUTORIAL_PROGRESS_FILL_DURATION_MS = 5000;
export const TUTORIAL_ACTION_BUTTON_HEIGHT = 52;
export const TUTORIAL_ACTION_BUTTON_GAP = 14;
export const TUTORIAL_ACTION_AREA_BOTTOM_OFFSET = 28;
export const OVERVIEW_ACTION_BUTTON_HEIGHT = 54;

export const TUTORIAL_TWO_BUTTON_ACTION_AREA_RESERVE =
  TUTORIAL_ACTION_AREA_BOTTOM_OFFSET +
  TUTORIAL_ACTION_BUTTON_HEIGHT * 2 +
  TUTORIAL_ACTION_BUTTON_GAP;
export const TUTORIAL_ONE_BUTTON_ACTION_AREA_RESERVE =
  TUTORIAL_ACTION_AREA_BOTTOM_OFFSET + TUTORIAL_ACTION_BUTTON_HEIGHT;
